### ISSUE TITLE
Olá, Victordop!

### ISSUE THREAD

**Issue by Felipe-Souza-Pereira-Lima** [Victordop/ola-mundo#1]
Eu vi que você é bom nessas coisas de HTML, e eu estou com um projeto Chamado [*Dsa Terminal*](https://github.com/Dsa-Terminal/Dsa-Terminal) Ele é um simulador de linux ubuntu e tem uma mini interface grafica EFI e queria saber se você quer participar da minha organização, o Terminal é pratico e eficiente tem umas coisas interessantes como:
http_client, webnews, etc!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Preciso de uma resposta rapida

**Comment by Victordop** [comment]
Olá, Felipe, tudo bem?
Gostaria de ajudar mas ainda estou bem "cru" no mundo da  programação e no momento estou com uns projetos paralelos a ela..
De qualquer forma, obrigado pelo convite!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Obg. Amanha te mando um convite para a organização [Dsa Terminal](https://github.com/Dsa-Terminal)

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Quantos anos você tem mesmo?

**Comment by Victordop** [comment]
> Obg. Amanha te mando um convite para a organização [Dsa Terminal](https://github.com/Dsa-Terminal)

Felipe, desculpe, quis dizer que não poderei participar...
Mas, novamente, obrigado pelo contato!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
A bom Ok

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Desculpa por oculpar seu tempp
